version: '3.7'

services:
  localdb:
    image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=WillBaumann365
      - ACCEPT_EULA=Y
    volumes:
      - "localdbdata:/var/opt/mssql"
  omdb:
    image: mljohns89/fourthwall-omdb:latest
    ports:
      - 8080:8080
    environment:
      - LOCAL_DB_HOST=localdb
volumes:
  localdbdata: