spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=fourthwall;useLOBs=false"
    username: "sa"
    password: "WillBaumann365"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
