spring:
  datasource:
    url: jdbc:sqlserver://${LOCAL_DB_HOST:localhost}:1433;databaseName=fourthwall;useLOBs=false
    username: "sa"
    password: "WillBaumann365"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  security:
    user:
      name: admin
      password: "WillBaumann365"
