create table [fourthwall].[dbo].[movies] (
    id int identity PRIMARY KEY,
    imdbID nvarchar(9) UNIQUE,
    title nvarchar(256),
    releaseDate datetime2,
    mpaRating nvarchar(5),
    runtimeInMinutes int,
    genre nvarchar(max),
    director nvarchar(256),
    writers nvarchar(max),
    actors nvarchar(max),
    plot nvarchar(max),
    language nvarchar(max),
    country nvarchar(max),
    awards nvarchar(max),
    poster nvarchar(max),
    metascore smallint,
    imdbRating decimal,
    imdbVotes bigint,
    type nvarchar(256),
    dvdReleaseDate datetime2,
    boxOfficeRevenue decimal(19,4),
    production nvarchar(1024),
    website nvarchar(max),
    response bit
)